---
title: "Wellcome LEAP Cholecystectomy (Gecko) study Site survey interim results"
date: today
date-format: "DD-MMMM YYYY"
format: html
editor: visual
theme: cerulean
execute:
  echo: false
  warning: false
---

```{r}
library(tidyverse)
library(scales)
source("functions.R")

source("site_survey_pull.R")
#save(site_survey_orig, file = "site_survey_orig.rda")
#load("site_survey_orig.rda")

n_records = nrow(site_survey_orig)
site_survey = site_survey_orig %>% 
  mutate(hosp_itu_bed = parse_number(hosp_itu_bed),
         train_n = parse_number(train_n))

xlab = "Number of hospitals"
```


::: {layout-ncol="1"}
```{r}

library(bslib)
library(bsicons)
library(shiny)

bslib::value_box(
  title = "GECKO",
  value = paste(n_records, "site surveys completed"),
  showcase = bs_icon("hospital"),
  p("Updated:"),
  p(format(Sys.time(), "%d-%b %Y")),
  theme_color = "info"
  )
```
:::

# Hospital demographics

::: {layout-ncol="2"}
```{r}
barplot_count(site_survey, hosp_type, "Hospital type", xlab = xlab)
```

```{r}
barplot_count(site_survey, hosp_fund, "Hospital funding", xlab = xlab)
```

```{r}
barplot_count(site_survey, hosp_itu_yn, "HDU or ITU facilities", xlab = xlab)
```

```{r}
histogram(site_survey, hosp_itu_bed, "Number of HDU/ITU beds", "Number of beds", "Number of hospitals")
```

```{r}
barplot_count(site_survey, hosp_hpb, "Specialised HPB team at your hospital", xlab = xlab)
```


```{r}
barplot_count(site_survey, hosp_hpb_path, "HPB: dedicated pathway for bile duct injury management", xlab = xlab)
```
:::

::: {layout-ncol="1"}

::: {.panel-tabset}

## Plot

```{r, fig.height = 5, fig.width=10}
mytreemap(site_survey, wb, hosp_hpb_oncall) +
  ggtitle("On-call services from the HPB team")

```


## Counts

```{r, fig.height=8, fig.width=10}
barplot_count(site_survey, hosp_hpb_oncall, "On-call services from the HPB team", xlab) +
  facet_wrap(~wb)
```
:::


::: {.panel-tabset}

## Plot
```{r, fig.height = 5, fig.width=10}
mytreemap(site_survey, wb, hosp_hpb_region) +
  ggtitle("On-call surgeons specialised in HPB")

```

## Counts

```{r, fig.width=12, fig.height = 5}
barplot_count(site_survey, hosp_hpb_region, "On-call surgeons specialised in HPB", xlab = xlab) +
  facet_wrap(~wb, ncol = 4) +
  scale_x_continuous(expand = expansion(mult = c(0, 0.3), add = c(0, 0)))
```


:::


```{r, fig.width=12, fig.height = 5}
barplot_count(site_survey, hosp_mis_yn, "Minimally invasive surgery equipment", xlab = xlab) +
  facet_wrap(~wb, ncol = 4) +
  scale_x_continuous(expand = expansion(mult = c(0, 0.36), add = c(0, 0)))
```

```{r, fig.width=14, fig.height = 5}
barplot_count(site_survey, hosp_mis_type, "Minimally invasive surgery equipment type", xlab = xlab) +
  facet_wrap(~wb, ncol = 4) +
  scale_x_continuous(expand = expansion(mult = c(0, 0.33), add = c(0, 0)))
```

```{r, fig.width=12, fig.height = 5}
barplot_count(site_survey, hosp_mis_image, "Routine intraoperative images", xlab = xlab) +
  facet_wrap(~wb, ncol = 4) +
  scale_x_continuous(expand = expansion(mult = c(0, 0.33), add = c(0, 0)))
```
:::

# Training in cholecystectomy

::: {layout-ncol="2"}
```{r}
barplot_count(site_survey, train_perform, "Trainees who perform gallbladder surgery", xlab = xlab)
```

```{r}
histogram(site_survey, train_n, "Trainees who perform gallbladder surgery", "Number of trainees", "Number of hospitals")
```
:::

::: {layout-ncol="1"}
```{r, fig.height = 5, fig.width=10}
mytreemap(site_survey, wb, train_grade) +
  ggtitle("Grade of trainees who perform gallbladder surgery")
```


::: {.panel-tabset}

## Plot
```{r, fig.height = 5, fig.width=10}
mytreemap(site_survey, wb, train_sim_yn) +
  ggtitle("Facilities for simulations training for cholecystectomies?")
```

## Counts

```{r, fig.height = 8, fig.width=10}
barplot_count(site_survey, train_sim_yn, "Facilities for simulations training for cholecystectomies?", xlab = xlab) +
  facet_wrap(~wb, ncol = 4)
```

:::

::: {.panel-tabset}

## Plot

```{r, fig.height = 5, fig.width=10}
mytreemap(site_survey, wb, train_sim_type) +
  ggtitle("Types of training simulation available")
```

## Counts

```{r, fig.height = 8, fig.width=10}
barplot_count(site_survey, train_sim_type, "Types of training simulation available", xlab = xlab) +
  facet_wrap(~wb, ncol = 4)
```

:::


::: {.panel-tabset}

## Plot

```{r, fig.height = 5, fig.width=10}
mytreemap(site_survey, wb, tain_chole) +
  ggtitle("Structured programmes/coaching for cholecystectomy training")
```

## Counts

```{r, fig.height = 8, fig.width=10}
barplot_count(site_survey, tain_chole, "Structured programmes/coaching for cholecystectomy training", xlab = xlab) +
  facet_wrap(~wb, ncol = 4)
```

:::

::: {.panel-tabset}

## Plot

```{r, fig.height = 5, fig.width=10}
mytreemap(site_survey, wb, train_bdi) +
  ggtitle("Structured programmes/coaching for bile duct injury training")
```

## Counts

```{r, fig.width = 12, fig.height = 10}
barplot_count(site_survey, train_bdi,
              "Structured programmes/coaching for bile duct injury training", high_n = 80, xlab = xlab) +
  facet_wrap(~wb, ncol = 4) +
  scale_x_continuous(expand = expansion(mult = c(0, 0.33), add = c(0, 0)))
```

:::


:::
